### ISSUE TITLE
Define the contents of .seqvars

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/mg-scripts#1]
From seq_proc_share.sh

**Comment by ElDeveloper** [comment]
Describe all environment variables, specifically if `output_dir` is declared here.

**Comment by jdereus** [comment]
job_template='<path to my>/bcl_template.sh'
output_dir=<wherever we put stuff>

again, output_dir is only defined in script if it needs to be run as a standalone due to other errors.  otherwise, output_dir is constant 

there is a maillist defined in case nothing is defined in sample sheet.

**Comment by ElDeveloper** [comment]
Great, thanks!!

**Comment by charles-cowart** [comment]
This issue appears resolved with the migration to the SPP codebase.
