### ISSUE TITLE
Add a check to remove empty FASTQ files

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/mg-scripts#12]
In some cases atropos or bowtie might produce empty FASTQ files due to all reads being filtered out. In those cases it would be best if we could remove the files altogether from the final destinations. Reason being that downstream tools don't always work well with empty files.

For example checking if the files are empty before GZipping them here might be best:

https://github.com/biocore/mg-scripts/blob/f34f6ab9e7835cda4ddd82879fb471c80b3c67fd/atropos_filter_parallel.sh#L79-L82

**Comment by charles-cowart** [comment]
This issue appears resolved with the migration to the SPP codebase. We have been filtering out files with file sizes under a set threshold for a while now.
