### ISSUE TITLE
E-mail at the end of the process

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/mg-scripts#13]
Currently e-mails are sent once the data is available on barnacle, but it would be useful if in addition e-mails could be sent out towards the end of the processing pipeline.

**Comment by ElDeveloper** [comment]
We might want to enable/disable this via a CLI parameter in case a run needs to be debugged/re-run/etc.

**Comment by charles-cowart** [comment]
This issue appears resolved with the migration to the SPP codebase. Note that the code that updates the user w/emails and/or other notifications is handled by Qiita, not SPP. SPP relays current status to Qiita and Qiita handles it.
