### ISSUE TITLE
Define contents of pbs-maui.sh

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/mg-scripts#3]
From seq_proc_share.sh

**Comment by jdereus** [comment]
pbs-maui.sh simply defines paths to the executable bits of torque and maui.  it is a global profile.sh script on the system.  simpler here to define a QSUB and QSTAT variable with paths to whatever executables will be available for testing.

**Comment by ElDeveloper** [comment]
Thanks, we'll make a note of this in the script. As @antgonza and I are working through these scripts we are expanding on the comments where it seems appropriate.

**Comment by charles-cowart** [comment]
This issue appears resolved with the migration to the SPP codebase.
