### ISSUE TITLE
Handle 2-color chemistry outputs (add polyG filtering)

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/mg-scripts#5]
The initial atropos command call (we are very close to determine what this will be) will need to change for 2-color chemistry runs.

**Comment by charles-cowart** [comment]
polyG filtering could be set in the [Bioinformatics] section of a sample-sheet, but I believe that we're  already past that now. The only current QCing I know of is human sequence filtering and adapter trimming.

This issue appears resolved with the migration to the SPP codebase.
