### ISSUE TITLE
report the samples that didn't make it to the end

### ISSUE THREAD

**Issue by antgonza** [biocore/mg-scripts#60]
Sometimes during processing samples fail after QC and they get lost during processing. We would like to add the list of samples and where did they fail to the Qiita's study analytical notes.

**Comment by charles-cowart** [comment]
Tentatively resolved with https://github.com/qiita-spots/qp-knight-lab-processing/pull/22

A list of samples lost during each stage of processing are written out to a new file named 'failed_samples.txt'. Will look into how to apply the metadata to the appropriate study's analytical notes.

**Comment by antgonza** [comment]
Solved in the current version.
