### ISSUE TITLE
include the number of reads at each state to the preparation information files

### ISSUE THREAD

**Issue by antgonza** [biocore/mg-scripts#61]
Add two new columns for each sample: `raw_reads`, `after_qc_reads` to the preparations.

**Comment by antgonza** [comment]
These are already part of the prep information file but it will be good to make the nan's be not applicable or something valid for ena.

**Comment by charles-cowart** [comment]
@antgonza After looking into this I admit I'm a little confused. I don't see mention of raw_reads or after_qc_reads anywhere in the mg-scripts, metagenomics-pooling-notebook, or qp-knight-lab-processing repositories. I'm not sure how these could already be part of the prep information file. Note I am considering only master/main branches.

**Comment by antgonza** [comment]
Their name are: non_host_reads, quality_filtered_reads, raw_reads, fraction_passing_quality_filter. Note that it will be good to _always_ write them, and when they do not apply use 'not applicable' as their value.

**Comment by antgonza** [comment]
Solved in the current version.
