### ISSUE TITLE
Use RTAComplete.txt to confirm that the folder is fully sync 

### ISSUE THREAD

**Issue by antgonza** [biocore/mg-scripts#63]
We should check that RTAComplete.txt is present and readable before continue to process a folder.

**Comment by charles-cowart** [comment]
Addressed in https://github.com/biocore/mg-scripts/pull/65

**Comment by antgonza** [comment]
@charles-cowart check [this](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword); this will allow you to automatically close the issues when merged.
