### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/mg-scripts#7]
We can use [this run](https://basespace.illumina.com/s/5yuCT6UE1e3Q) to test the BCL portion of the code. Note, we'll need to add remove all files BCL files except for 0001* to 0169* (if we want to produce non-empty FASTQ files) or just include 0001* if we don't mind having only Undetermined reads.

This command gets the job done in either case:

```
bcl2fastq \
--sample-sheet 16SiSeq/SampleSheet.csv \
--minimum-trimmed-read-length 1 \
--mask-short-adapter-reads 1 \
-R 16SiSeq/ \
-o iseq-fastqs-removing-data \
--loading-threads 4 \
--processing-threads 8 \
--writing-threads 2 \
--tiles s_1_1101 --ignore-missing-bcls --ignore-missing-filter --ignore-missing-positions
--create-fastq-for-index-reads
```

**Comment by charles-cowart** [comment]
This issue appears resolved with the migration to the SPP codebase.
