### ISSUE TITLE
Add diagnostic plots with MultiQC

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/mg-scripts#9]

**Comment by ElDeveloper** [comment]
For completeness, these are two of the changes that need to occur that @antgonza has noted:

1) For bowtie, we need to change the first pipe in this line to include a redirect to stderr:



https://github.com/biocore/mg-scripts/blob/f34f6ab9e7835cda4ddd82879fb471c80b3c67fd/atropos_filter_parallel.sh#L79


2) For atropos we need to save the logs as JSON. The following line:

https://github.com/biocore/mg-scripts/blob/f34f6ab9e7835cda4ddd82879fb471c80b3c67fd/atropos_filter_parallel.sh#L48

Should be updated as:
```
atropos --threads 16 ${atropos_param} --stats 'both' --report-file ${atropos_qc_output}/atropos_logs/${filename1_short}.json--report-formats json -o ${atropos_qc_output}/${filename1_short}.fastq -p ${atropos_qc_output}/${filename2_short}.fastq -pe1 $filename1 -pe2 $filename2
```

Also, in order to run atropos [this PR](https://github.com/ewels/MultiQC/pull/1132) submitted by @antgonza needs to be merged in the MultiQC repo.

**Comment by jdereus** [comment]
Why the need for json?

**Comment by ElDeveloper** [comment]
As I understand, those are the files that the atropos plugin for multiqc 
expects. Is that right @antgonza?

**Comment by antgonza** [comment]
That's correct, the atropos/multiqc plugin expects them as json; if txt, they will not get summarized ...

**Comment by charles-cowart** [comment]
This issue appears resolved with the migration to the SPP codebase. I didn't review all of the above options for MultiQC, but we have been running jobs with MultiQC support for a little while now, and everyone appears content with the output.
