### ISSUE TITLE
Differentiate exceptions by objects not messages

### ISSUE THREAD

**Issue by wasade** [biocore/mg-scripts#93]
`is_mapping_file` differentiates error types based on exception [messages](https://github.com/biocore/mg-scripts/blob/70462fe42b1af462e657a12d565bc4658500ae92/sequence_processing_pipeline/Pipeline.py#L361-L366). This is prone to bugs from maintenance as if an error message changes, this code will silently stop working.

**Comment by charles-cowart** [comment]
Closing issue, as #103 was merged.
